#
# Project infos
site_name: Get started on SAP BTP creating a Hello World app with SAPUI5/Fiori
copyright: See this mission also on SAP Discovery Center 

# Configuration
theme:
  font: false
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
#    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.tracking
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Customization
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SAP-samples/btp-hello-world-fiori

extra_css:
  - 'stylesheets/extra.css'




# Navigation
nav:
- 'Home':
  - 'About this Mission' : pages/1_discover/1_mission_story.md
  - 'Discover UI5' : pages/1_discover/2_learn_ui5.md    
- 'Setup BTP':
  - 'Setup an Enterprise Account':
    - 'Prerequisites' : pages/2_setup_ea/1_prereq_e_account.md
    - 'Start Booster' : pages/2_setup_ea/2_booster_step_1.md
    - 'Execute Booster' : pages/2_setup_ea/3_booster_step_234.md
    - 'Check Results' : pages/2_setup_ea/4_booster_check_subacc.md
  - 'Setup a Trial Account':
    - 'Get Trial Account' : pages/2_setup_trial/1_get_trial.md
    - 'Setup Build Work Zone' : pages/2_setup_trial/4_setup_workzone.md
- 'Develop':  
  - 'Setup BAS' : pages/3_develop/1_setup_bas.md       
  - 'Start from Template' : pages/3_develop/2_create_app.md
  - 'Test and Preview' : pages/3_develop/3_test_app_local.md
  - 'Build and Deploy' : pages/3_develop/4_build_mta.md
- 'Setup Work Zone':  
  - 'Prepare Work Zone' : pages/4_workzone/5_prepare_launchpad.md
  - 'Create Site' : pages/4_workzone/6_create_launchpad_site.md
  - 'Add App to Site' : pages/4_workzone/7_addapp_to_launchpad.md
- 'Setup CI/CD':
  - 'Use Git' : pages/5_git/5_1_usegit.md
  - 'Clone a Repo' : pages/5_git/5_2_gitclone.md
  - 'Setup CI/CD' : pages/5_git/5_3_cicd.md
